FROM python:{{ python_version }}-slim

WORKDIR /app

COPY requirements.txt .
RUN pip insatll --no-cache-dir -r requirements.txt

COPY . .

EXPORT 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]